@accessToken = call auth method first

###
# @name=Проверка аутентификации
GET http://{{host}}/api/olo/sayHello
Authorization: {{accessToken}}

###
# @name=Получение всех виджетов, которые добавлены у пользователя
GET http://{{host}}/api/olo/getWidgets
Authorization: {{accessToken}}

###
# @name=Добавить виджет пользователя
POST http://{{host}}/api/olo/addWidget
Authorization: {{accessToken}}
Content-Type: application/json

{
  "data": "Тестовый виджет"
}

###
# @name=Обновить виджет пользователя
POST http://{{host}}/api/olo/updateWidget
Authorization: {{accessToken}}
Content-Type: application/json

{
  "id": 1,
  "data": "Тестовый виджет"
}

###
# @name=Удалить виджет у пользователю
POST http://{{host}}/api/olo/deleteWidget
Authorization: {{accessToken}}
Content-Type: application/json

{
  "widgetId": 1
}

###
# @name=Получение всех статей
GET http://{{host}}/api/olo/articles
Authorization: {{accessToken}}

###
# @name=Получение всех статей, которые добавлены у пользователя
GET http://{{host}}/api/olo/getUserArticles
Authorization: {{accessToken}}

###
# @name=Добавить статью пользователя
POST http://{{host}}/api/olo/addArticleForUser
Authorization: {{accessToken}}
Content-Type: application/json

{
  "articleId": 1
}

###
# @name=Удалить статью у пользователю
POST http://{{host}}/api/olo/deleteArticleForUser
Authorization: {{accessToken}}
Content-Type: application/json

{
  "articleId": 1
}

